"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
# from celery.schedules import crontab
from __No_Commit.config import CONFIG_ENV_TYPE

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&!vi)sy@-wmt$!z3%+e3^-u29sz)!hf#t4bjq)uu=cu1j%2v0m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False if CONFIG_ENV_TYPE == "live" else True
#DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1']

CURRENT_REVISION = "v1.0.1" 

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django_celery_results',
    # 'django_celery_beat',

    #3rd part
    'crispy_forms',
    'corsheaders',

    #apps
    'f_1_1_customers.apps.F11CustomersConfig',
    'f_1_2_sites.apps.F12SitesConfig',
    'f_7_1_accounts.apps.F71AccountsConfig',
    'f_7_2_pages.apps.F72PagesConfig',
    'accu_dashboard.apps.AccuDashboardConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'f_7_1_accounts.middleware.SessionTimeoutMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'f_7_1_accounts.middleware.LoginCodeMiddleware',
    'corsheaders.middleware.CorsMiddleware',

] 

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            'environment': 'main.jinja2.environment',
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },   
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
if CONFIG_ENV_TYPE == 'local':

    DB_NAME = 'local_db'
    DB_HOST = '127.0.0.1'
    DB_PASS = ''
    
    CURRENT_URL = 'http://127.0.0.1:8000'
    INSTALLED_APPS.append('sslserver')


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': "10.16.150.77:1521/soca",
        'USER': 'smartw_view_only',
        'PASSWORD': "smartw_view_only",
       
    }
}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR)+'/db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    {
        'NAME': 'f_7_1_accounts.password.password_validation.CustomValidator', # 追記
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = 'select_customer' 
LOGOUT_REDIRECT_URL = 'login' 

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Other Django configurations...
# Celery application definition
# http://docs.celeryproject.org/en/v4.0.2/userguide/configuration.html
CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Tokyo'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'support@tpcompany.net'
OSCAR_FROM_EMAIL = 'リードプラス マイクロソフトメディア運営事務局 <support@tpcompany.net>'
EMAIL_HOST_PASSWORD = 'vkadjrynaiyvgkcc'
PASSWORD_RESET_TIMEOUT  = 604800 #7 Ngày
# PASSWORD_RESET_TIMEOUT  = 600 #10p
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_EXPIRE_SECONDS = 3600  # 1 hour
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_TIMEOUT_REDIRECT = 'login'
TOOL_NAME = 'ACCU-V1'
CORS_ALLOW_ALL_ORIGINS = True

DEFAULT_SCRET_KEY = 'UKTJUFPDLR4OLFEJ'